---
title: "Assignment 2"
subtitle: ""
author: "Raghav Sinha"
date: today
date-format: long
abstract: ""
number-sections: true
bibliography:
format:
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
editor: 
  markdown: 
    wrap: 72
---

```{r}
#| include: false
#| warning: false
#| message: false

library(ggplot2)
library(readr)
library(tibble)
library(knitr)
library(kableExtra)
library(dplyr)
library(MASS)
library(caret)
library(car)
library(broom)
library(tidyr)
library(Hmisc)
library(Pmisc)
```

## Motorcycle Deaths
```{r}
theUrl = "http://pbrown.ca/teaching/appliedstats/data/motorcycle.rds"
theFile = basename(theUrl)
if (!file.exists(theFile)) download.file(theUrl, theFile)
x = readRDS(theFile)
```
```{r}
x$dateInt = as.integer(x$date)
x$logMonthDays = log(Hmisc::monthDays(x$date))
x$month = factor(format(x$date, "%b"), levels = format(ISOdate(2000, 1:12, 1), "%b"))
res = glm(killed ~ offset(logMonthDays) + dateInt + month, data = x, family = poisson(link = "log"))
newdata = data.frame(date = seq(as.Date("1975/1/1"), as.Date("2030/1/1"), by = "month"))
newdata$dateInt = as.integer(newdata$date)
newdata$logMonthDays = log(30)
newdata$month = "Mar"
pred1 = predict(res, newdata)
newdata$month = format(newdata$date, "%b")
pred2 = predict(res, newdata)
plot(x$date, x$killed, cex = 0.2, log = "y", xlab = "")
matlines(newdata$date, exp(cbind(pred1, pred2)), lty = 1)
```

## Heat

```{r}
heatUrl = "http://pbrown.ca/teaching/appliedstats/data/sableIsland.rds"
dir.create("cache", showWarnings = FALSE)
heatFile = file.path("cache", basename(heatUrl))
if (!file.exists(heatFile)) download.file(heatUrl, heatFile)
heat = readRDS(heatFile)
names(heat) = gsub("[.]+C[.]","", names(heat))
heat$Date = as.Date(heat$Date)
heat$month = as.numeric(format(heat$Date, "%m"))
heat$summer = heat$month %in% 5:10
```

```{r}
heat[100, ]
```

```{r}
heat$dateInt = as.integer(heat$Date)
heat$yearFac = factor(format(heat$Date, "%Y"))
heatSub = heat[heat$summer & !is.na(heat$Max.Temp), ]
library("mgcv")
res1 = gam(update.formula(Max.Temp ~ s(dateInt, pc = as.integer(as.Date("1990/7/1")), k = 100) + s(yearFac, bs = "re"), Pmisc::seasonalFormula(period = 365.25, harmonics = 1:2, var = "dateInt")), data = heatSub, method = "ML", optimizer = "efs")
res2 = gam(update.formula(Max.Temp ~ s(dateInt, pc = as.integer(as.Date("1990/7/1")), k = 4) + s(yearFac, bs = "re"), Pmisc::seasonalFormula(period = 365.25, harmonics = 1:2, var = "dateInt")), data = heatSub, method = "ML", optimizer = "efs")
res3 = gam(update.formula(Max.Temp ~ s(dateInt, pc = as.integer(as.Date("1990/7/1")), k = 100), Pmisc::seasonalFormula(period = 365.25, harmonics = 1:2, var = "dateInt")), data = heatSub, method = "ML", optimizer = "efs")
```

```{r}
res1$formula
```

```{r}
Syear = unique(heatSub$yearFac)
predYear = do.call(cbind, predict(res1, newdata = data.frame(yearFac = Syear, dateInt = 0), type = "terms", terms = "s(yearFac)", se.fit = TRUE)) %*% Pmisc::ciMat()
newdat = data.frame(Date = seq(as.Date("1900/1/1"), as.Date("2035/12/31"), by = "2 weeks"), yearFac = Syear[1])
newdat$dateInt = as.integer(newdat$Date)
predTrend = do.call(cbind, predict(res1, newdat, type = "terms", terms = "s(dateInt)", se.fit = TRUE)) %*% Pmisc::ciMat()
newheat = predict(res1, newdata = newdat, type = "lpmatriheat")
simCoef <- rmvn(10, coef(res1), vcov(res1))
isTrend = grep("s[(]dateInt", colnames(newheat))
simTrend = tcrossprod(newheat[, isTrend], simCoef[, isTrend])
```

```{r}
Syear = as.numeric(as.character(Syear))
matplot(Syear, predYear, xlab = "Degrees C", cex = c(1, 0, 0), pch = 16, col = "black")
segments(Syear, predYear[, 2], Syear, predYear[, 3], lwd = 0.5)
matplot(newdat$Date, simTrend, type = "l", lty = 1, col = RColorBrewer::brewer.pal(ncol(simTrend), "Paired"), xaxt = "n", xaxs = "i", yaxs = "i", ylim = range(predTrend), xlab = "")
matlines(newdat$Date, predTrend, lty = c(1, 2, 2), col = "black", lwd = 2)
forX = as.Date(ISOdate(seq(1880, 2050, by = 25), 1, 1))
axis(1, forX, format(forX, "%Y"))
```

